apiVersion: v1
kind: Secret
metadata:
  name: veterinaria-secrets
  namespace: veterinaria
type: Opaque
stringData:
  DB_PASSWORD: rootpassword
  JWT_SECRET: clave-secreta-jwt-veterinaria-2025-duoc-uc-segura
